source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


platform :ios, '8.0'

target 'MZControls_Example' do
  pod 'MZControls', :path => '../'

  target 'MZControls_Tests' do
    inherit! :search_paths

    
  end
end
